[package]
name = "lktrace"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simplelog = "0.12"
clap = { version = "4.5.4", features = ["derive"] }
once_cell = "1.19.0"
#anyhow = "1.0"
#colored = "2.1.0"
